name: Update docusaurus

on:
  workflow_dispatch:

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest
          yarn add @docusaurus/theme-mermaid
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: upgrade docusaurus
